# Generated by Django 4.1.3 on 2022-12-20 10:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('stream', models.CharField(choices=[('Computer Science', 'Computer Science'), ('Business Administration', 'Business Administration'), ('Management', 'Management'), ('Marketing', 'Marketing'), ('Accounting', 'Accounting')], max_length=200)),
                ('school', models.CharField(max_length=200)),
                ('degree', models.CharField(choices=[('Bachelors', 'Bachelors'), ('Masters', 'Masters'), ('Associates', 'Associates'), ('Doctorates', 'Doctorates'), ('HighSchools', 'HighSchools')], max_length=200)),
                ('job_title', models.CharField(max_length=200)),
                ('skills', models.CharField(max_length=200)),
                ('experiance', models.IntegerField()),
                ('company', models.CharField(max_length=200, null=True)),
                ('phone', models.IntegerField(unique=True)),
                ('email', models.EmailField(max_length=200, unique=True)),
                ('linkdin', models.URLField(unique=True)),
                ('Twitter', models.URLField(null=True, unique=True)),
                ('github', models.URLField(null=True, unique=True)),
                ('alt_phone', models.IntegerField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=100)),
                ('DOB', models.DateField()),
                ('profile_photo', models.ImageField(blank=True, upload_to='register/image')),
                ('location', models.CharField(max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('full_name', models.CharField(default=False, max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=12)),
                ('confirm_password', models.CharField(max_length=12)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
