# Generated by Django 4.1.7 on 2023-03-04 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('selling_price', models.FloatField()),
                ('discounted_price', models.FloatField()),
                ('description', models.TextField()),
                ('brand', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('M', 'Mobile'), ('L', 'Laptop'), ('TW', 'Top Wear'), ('BW', 'Bottom Wear'), ('A', 'Atta'), ('C', 'Chhola'), ('CO', 'Cooking Oil'), ('K', 'Kitchen'), ('R', 'Rice'), ('DP', 'Dal/Pulses'), ('N', 'Nuts'), ('P', 'Pasta & Noodles'), ('SO', 'Special Offer')], max_length=2)),
                ('product_image', models.ImageField(upload_to='product_img')),
                ('specifications', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
