# Generated by Django 4.1.3 on 2022-12-21 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0002_myfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myfile',
            name='description',
        ),
        migrations.RemoveField(
            model_name='myfile',
            name='uploaded_at',
        ),
    ]
