# Generated by Django 4.1.7 on 2023-03-04 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0002_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_image',
        ),
    ]
