# Generated by Django 4.1.3 on 2022-12-28 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0004_contacts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pricing_Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tokens', models.IntegerField(default=0)),
                ('subscription', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Purchased_Subcription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='space.pricing_plan')),
                ('user_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='space.user_profile')),
            ],
        ),
        migrations.DeleteModel(
            name='MyFile',
        ),
        migrations.AddField(
            model_name='contacts',
            name='subscription',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='contacts',
            name='tokens',
            field=models.IntegerField(default=5),
        ),
    ]
