# Generated by Django 4.1.3 on 2022-12-29 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0006_customuser_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='token',
            new_name='tokens',
        ),
    ]
